### ISSUE TITLE
please Add Download Button

### ISSUE THREAD

**Issue by michaelolivar** [zen-audio-player/zen-audio-player.github.io#275] opened 2017-11-17 16:58 UTC
please add download button in next update for mp3 and mp4 file, hope my pull request will granted :) :+1:

**Comment by shakeelmohamed** [comment] 2017-11-17 17:50
Thanks for your request @michaelolivar.
Closing as dupe of #271, due to legal issues we will not add download functionality for YouTube videos.

**Closed by shakeelmohamed** 2017-11-17 17:50 UTC
Labels: wontfix
