### ISSUE TITLE
Demo link does nothing in Microsoft Edge or Internet Explorer

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#42] opened 2015-10-10 07:35 UTC
Using Microsoft Edge, the demo link doesn't do anything. The URL clearly changes, but it just dies (could be a race condition with jQuery loading before the YouTube API). There are no JavaScript console errors.

edit: Non-Windows users can get free VMs from Microsoft's website! https://dev.windows.com/en-us/microsoft-edge/tools/vms/

![image](https://cloud.githubusercontent.com/assets/1480063/10409930/b3b76c46-6ee6-11e5-90f3-49b8e256aa99.png)

**Comment by BeigeBadger** [comment] 2015-10-25 00:37
I had a good crack at this one today but was unable to make any progress. I tried a few avenues:

1. Using the HTML5 History attribute in JS.
2. Setting the origin of the YT player as per http://stackoverflow.com/questions/20501010/youtube-api-onplayerready-not-firing.
3. Removing display: none and/or setting the player to display off the page as per http://stackoverflow.com/questions/17078094/youtube-iframe-player-api-onstatechange-not-firing
4. Adding autoplay=1 as per http://stackoverflow.com/questions/6246939/start-play-embedded-iframe-youtube-video-on-click-of-an-image/28498814#28498814

The problem is that `onYouTubeIframeAPIReady` isn't being called in IE when the postback occurs. Thus `player` is null and none of the events get wired up.

The flow in Chrome on postback is:
* demo click handler
* `document.ready` function
* `onYTIframeAPIReady` function
* `onPlayerReady` function

In IE/Edge it is:
* demo click handler
* `document.ready` function

I'm not sure what is supposed to call `onYTIframeAPIReady` but it seems broken in IE never the less.

**Comment by shakeelmohamed** [comment] 2015-10-27 02:44
Thanks for the effort on this @BeigeBadger! I will dig into this when I have some spare time

**Comment by shakeelmohamed** [comment] 2015-11-30 06:14
I tried some magic on the `42` branch, and no luck. Edge support seems non-trivial

**Comment by moen-io** [comment] 2016-01-06 10:56
@shakeelmohamed What sort of solution are you looking for here? Another option could be to use the method described in the [iframe api documentation](https://developers.google.com/youtube/iframe_api_reference?hl=en)

**Comment by shakeelmohamed** [comment] 2016-01-06 17:31
@moen-io We were using the recommended method at one point, it may be worth revisiting again. Did you see 9be3cecdff43e6c888e93c1ad89d22bc15efbf7b? We can't reliably depend on JS scripts loading in order of inclusion.

> What sort of solution are you looking for here?

A robust one :smile:

**Comment by moen-io** [comment] 2016-01-06 18:09
@shakeelmohamed Under what circumstances do scripts not load in order of inclusion? Browsers are required to load scripts in the order they are encountered unless specifically marked async. The reason `https://www.youtube.com/iframe_api` behaves strangely is because it does, in fact, attempt to load `www-widgetapi.js` async. Thus the only way to ensure that `everything.js` loads first is to place it higher in the load order.

**Comment by shakeelmohamed** [comment] 2016-01-06 18:29
>  Browsers are required to load scripts in the order they are encountered unless specifically marked async.

Thanks for correcting me, I forgot about that. I'm going to re-open #115 with a couple of comments

**Closed** 2016-01-10 22:30 UTC
Labels: bug, in progress, up for grabs
