### ISSUE TITLE
Time-slider tooltip

### ISSUE THREAD

**Issue by eirism** [zen-audio-player/zen-audio-player.github.io#132] opened 2016-01-14 16:31 UTC
When #131 is fixed,it would be nice to have a tooltip on the timeSeek slider, like the Youtube player. I think we should use the default tooltip behavior, show, to only show it when hovering over the slider.

To prevent the tooltip from colliding into the text above/below it (depends on tooltip placement) we will also need to add some air between the slider and the surrounding text.

**Comment by shakeelmohamed** [comment] 2016-03-12 20:39
Since this is basically a dupe of #131, we don't need to do it once #131 goes in.

Leaving this open until plyr is working

**Comment by shakeelmohamed** [comment] 2016-05-01 06:43
Plyr support has been merged in with #176, there is a tooltip for the time slider 🎉 . Give it a try!

**Closed by shakeelmohamed** 2016-05-01 06:43 UTC
Labels: wontfix
